<a href="https://colab.research.google.com/github/sselgrad23/Pandas-Tutorial-For-Beginners/blob/main/pandas_tutorial_lesson_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Filtering Data

In [1]:
import pandas as pd

In [2]:
olympics_data_sheets = pd.read_excel('https://github.com/KeithGalli/complete-pandas-tutorial/raw/refs/heads/master/data/olympics-data.xlsx', sheet_name=['bios', 'results'])

In [3]:
bios = olympics_data_sheets['bios']
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [4]:
bios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 11.1+ MB

In [5]:
bios.loc[bios['height_cm'] > 220] # Filtering out athletes greater than 220cm tall

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5673,5696,Gunther Behnke,1963-01-19,Leverkusen,Nordrhein-Westfalen,GER,Germany,221.0,114.0,NaN
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
6978,7013,Arvydas Sabonis,1964-12-19,Kaunas,Kaunas,LTU,Lithuania Soviet Union,223.0,122.0,NaN
89070,89782,Yao Ming,1980-09-12,Xuhui District,Shanghai,CHN,People's Republic of China,226.0,141.0,NaN
89075,89787,Roberto Dueñas,1975-11-01,Madrid,Madrid,ESP,Spain,221.0,137.0,NaN
120266,122147,Zhang Zhaoxu,1987-11-18,Binzhou,Shandong,CHN,People's Republic of China,221.0,110.0,NaN

In [6]:
bios.loc[bios['height_cm'] > 215, ['name', 'height_cm']].head(5) # Also only grabbing name and height

                       name  height_cm
5089     Viktor Pankrashkin      220.0
5583   Paulinho Villas Boas      217.0
5673         Gunther Behnke      221.0
5716               Uwe Blab      218.0
5781         Tommy Burleson      223.0

In [7]:
# Alternative syntax
bios[bios['height_cm'] > 215][['name', 'height_cm']].head(5)

                       name  height_cm
5089     Viktor Pankrashkin      220.0
5583   Paulinho Villas Boas      217.0
5673         Gunther Behnke      221.0
5716               Uwe Blab      218.0
5781         Tommy Burleson      223.0

Use & and round brackets to add additional conditions:

In [8]:
bios[(bios['height_cm'] > 215) & (bios['born_country'] == 'USA')]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN

Filtering using string operations. By default, str.contains is case-sensitive. This can be toggled with case=False.

In [9]:
bios[bios['name'].str.contains("sophie", case=False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
19566,19705,Sophie von Weiler,1958-12-24,NaN,NaN,NaN,Netherlands,159.0,62.0,NaN
20495,20640,Sophie Moressée-Pichot,1962-04-03,Sissonne,Aisne,FRA,France,174.0,63.0,NaN
45527,45872,Sophie Simard,1978-09-20,NaN,NaN,NaN,Canada,168.0,61.0,NaN
46389,46737,Sophie Kamoun,1967-06-08,NaN,NaN,NaN,France,173.0,55.0,NaN
60479,60912,Sophie Berge,1964-07-05,Nantes,Loire-Atlantique,FRA,France,171.0,65.0,NaN
...,...,...,...,...,...,...,...,...,...,...
139792,143278,Sophie Koch,1997-10-04,Parchim,Mecklenburg-Vorpommern,GER,Germany,170.0,65.0,NaN
139796,143282,Lea-Sophie Friedrich,2000-01-07,Lübeck,Schleswig-Holstein,GER,Germany,NaN,NaN,NaN
140341,143848,Sophie Becker,1997-05-16,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
144150,147828,Sophie Ash,1996-11-07,Brisbane,Queensland,AUS,Australia,NaN,NaN,NaN
145456,149182,Sophie Sorschag,1998-11-14,Villach,Kärnten,AUT,Austria,NaN,NaN,NaN

Regex syntax is also allowed. | means or. Regex can be turned off with regex=False.

In [10]:
bios[bios['name'].str.contains("sophie|samantha", case=False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
19566,19705,Sophie von Weiler,1958-12-24,NaN,NaN,NaN,Netherlands,159.0,62.0,NaN
20495,20640,Sophie Moressée-Pichot,1962-04-03,Sissonne,Aisne,FRA,France,174.0,63.0,NaN
28490,28703,Samantha Ferrari,1973-09-25,Muggiò,Monza e Brianza,ITA,Italy,NaN,NaN,NaN
45527,45872,Sophie Simard,1978-09-20,NaN,NaN,NaN,Canada,168.0,61.0,NaN
46389,46737,Sophie Kamoun,1967-06-08,NaN,NaN,NaN,France,173.0,55.0,NaN
...,...,...,...,...,...,...,...,...,...,...
140341,143848,Sophie Becker,1997-05-16,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
143545,147198,Samantha Schultz,1992-03-27,NaN,NaN,NaN,United States,NaN,NaN,NaN
144150,147828,Sophie Ash,1996-11-07,Brisbane,Queensland,AUS,Australia,NaN,NaN,NaN
144472,148164,Samantha Ahn Kolowratová,1996-07-12,Praha (Prague),Hlavní město Praha,CZE,Czechia,170.0,NaN,NaN
145456,149182,Sophie Sorschag,1998-11-14,Villach,Kärnten,AUT,Austria,NaN,NaN,NaN

You can also use .isin to only keep rows where a certain column is one of the specified values:

In [11]:
bios[bios['born_country'].isin(['USA', 'Canada']) & (bios['name'].str.startswith("Samantha"))]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
106334,107424,Samantha Harvey,1972-10-13,New York,New York,USA,Brazil,165.0,53.0,NaN
116264,117651,Samantha Peszek,1991-12-14,Indianapolis,Indiana,USA,United States,152.0,50.0,NaN
126509,128872,Samantha Roberts,2000-04-21,Memphis,Tennessee,USA,Antigua and Barbuda,172.0,64.0,NaN
136899,140135,Samantha Paisley,2002-11-14,Salt Lake City,Utah,USA,United States,NaN,NaN,NaN
137667,141032,Samantha Dirks,1992-12-18,Los Angeles,California,USA,Belize,NaN,NaN,NaN

query can be used to filter rows with less clunky syntax:

In [12]:
bios.query('born_country == "GBR" and NOC == "France"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
118,119,Archibald Warden,1869-05-11,Edinburgh,Scotland,GBR,France,NaN,NaN,1943-10-07
17058,17176,Will Davis,1877-07-28,Bristol,England,GBR,France,NaN,NaN,1932-12-28
17698,17819,William Anderson,1859-06-27,Edinburgh,Scotland,GBR,France,NaN,NaN,1923-04-26
17699,17820,Willie Attrill,1868-01-01,Cowes,England,GBR,France,NaN,NaN,1939-01-01
17700,17821,John Braid,1869-01-29,Kirkcaldy,Scotland,GBR,France,NaN,NaN,1960-04-09
17706,17827,Alfred Schneidau,1867-02-05,Camden,England,GBR,France,NaN,NaN,1940-01-24
17708,17829,Henry Terry,1869-05-27,Huddersfield,England,GBR,France,NaN,NaN,1952-07-27
17709,17830,Philip Tomalin,1856-04-10,Kensington,England,GBR,France,NaN,NaN,1940-02-12
17729,17850,Émile Thubron,1861-07-15,Boldon,England,GBR,France,NaN,NaN,1927-05-22
36688,36982,René Guissart,1929-09-12,Hampstead,England,GBR,France,NaN,NaN,2014-09-08
46867,47216,Bill Burgess,1872-06-15,Rotherham,England,GBR,France,185.0,95.0,1950-07-05
67391,67902,Laureen Beckles,1958-08-30,Islington,England,GBR,France,160.0,52.0,NaN
67515,68026,Émile Ali Khan,1902-06-06,Battle,England,GBR,France,180.0,69.0,NaN
80277,80928,Anita de Saint Quentin,1901-11-13,Moffat,Scotland,GBR,France,163.0,NaN,NaN
100277,101126,Sébastien Vassoney,1975-09-26,Manchester,England,GBR,France,180.0,80.0,NaN
114858,116181,Jess Harrison,1977-10-27,Sheffield,England,GBR,France,170.0,61.0,NaN
116870,118287,Jane Moulin,1877-04-05,Hackney,England,GBR,France,NaN,NaN,1947-07-05
119709,121538,Christopher Patte,1990-03-29,London,England,GBR,France,176.0,66.0,NaN
125400,127745,Ben Cavet,1994-01-01,Maidstone,England,GBR,France,180.0,70.0,NaN
125411,127756,Lloyd Jones,1988-08-01,Cardiff,Wales,GBR,France,185.0,NaN,NaN
127694,130165,Shannon Izar,1993-05-08,Lambeth,England,GBR,France,172.0,68.0,NaN
136922,140158,Margot Ravinel,2002-06-07,Frimley,England,GBR,France,NaN,NaN,NaN