<a href="https://colab.research.google.com/github/sselgrad23/Pandas-Tutorial-For-Beginners/blob/main/pandas_tutorial_lesson_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Basics for Beginners

In [ ]:
import pandas as pd

For the sake of this tutorial, we manually create a small dataframe and fill it up with values. Typically, we would load some other file first and create a dataframe from it using pandas.

In [ ]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns = ['a','b','c'], index = ['x', 'y', 'z'])

In [ ]:
df.head() # Outputs first 5 rows

   a  b  c
x  1  2  3
y  4  5  6
z  7  8  9

In [ ]:
df.head(1) # First row

   a  b  c
x  1  2  3

In [ ]:
df.tail(2) # Last 2 rows

   a  b  c
y  4  5  6
z  7  8  9

In [ ]:
print(df.columns)
print(df.index)
print(df.index.to_list())

Index(['a', 'b', 'c'], dtype='object')
Index(['x', 'y', 'z'], dtype='object')
['x', 'y', 'z']

In [ ]:
df.info() # Info about the dataframe itself

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      int64
 1   b       3 non-null      int64
 2   c       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0+ bytes

In [ ]:
df.describe() # Gives meaningful stats about our data

         a    b    c
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [ ]:
df.nunique() # Number of unique values in each column

a    3
b    3
c    3
dtype: int64

In [ ]:
df['a'].unique() # Number of unique values in column a

array([1, 4, 7])

In [ ]:
df.shape # Shape of dataframe

(3, 3)

In [ ]:
df.size # Total number of items

9